import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="container mx-auto min-h-screen h-screen px-2 flex flex-col justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-20 flex-1 flex flex-col justify-center items-center">
        <h1 className="text-6xl font-bold m-0 text-center">
          Welcome to{" "}
          <a
            href="https://nextjs.org"
            className="text-blue-600 no-underline hover:underline"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-center text-2xl leading-6 mt-8 mb-4">
          Get started by editing{" "}
          <code className="bg-gray-100 p-3 rounded-md font-mono text-lg leading-4">
            pages/index.js
          </code>
        </p>

        <div className="max-w-3xl grid md:grid-cols-2 mt-12">
          <a
            href="https://nextjs.org/docs"
            className="m-4 p-6 border border-gray-200 rounded-xl transition duration-200 hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="font-bold text-2xl mb-4">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="m-4 p-6 border border-gray-200 rounded-xl transition duration-200 hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="font-bold text-2xl mb-4">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="m-4 p-6 border border-gray-200 rounded-xl transition duration-200 hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="font-bold text-2xl mb-4">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="m-4 p-6 border border-gray-200 rounded-xl transition duration-200 hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="font-bold text-2xl mb-4">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="w-full h-24 border-t border-gray-300 flex justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
